### ISSUE TITLE
Rack Geräte

### ISSUE THREAD

**Issue by MINAqwq** [MINAqwq/VR-NetRack#6]
- [ ] Router
- [x] Switch
- [ ] Patchfeld
- [ ] Server

> /LF420	Rack-Geräte 
Es sollen verschiedene Geräte realisiert werden (rein optisch mit entsprechenden verbindbaren Anschlüssen, wie Netzwerkports, Stromanschluss, etc.). Dazu sollen mindestens ein Routermodell, ein Switchmodell, ein Patchfeld, sowie ein Server gehören, welche optisch realen Geräten nachempfunden sind.

**Comment by OfficialPixelBrush** [comment]
Technically still open, but the original project members have moved on from this. Good luck to whoever will resume work on this!
